### ISSUE TITLE
ClinVar override not working as expected for recessive search

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2725]
**Describe the bug**
In RGP_248, an RNU4ATAC variant pair containing a LP variant in ClinVar in trans with a noncoding_transcript_exon_variant is not being returned when you add the noncoding_transcript_exon_variant annotation for one of the variants in a recessive search. I have to allow noncoding_transcript_exon_variant for both first and second hits in order to return the variant pair, but that adds too many variants to the search results.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/acb54e270b560d3a0d4319620d959218?page=1&sort=pathogenicity

**Scope of the bug**
Only have a use case in this family but assume this is a systemic issue

**Screenshots**
For reference, this is the desired variant pair: 
![image](https://user-images.githubusercontent.com/67653781/169535628-4da8b6e9-41f3-4059-b0d2-2f38d4c21529.png)

**Comment by hanars** [comment]
this bug is now fixed and that compound het pair is coming back in that search

**Comment by hanars** [comment]
The second hit is not in clinvar so you need to make sure "non coding transcript exon variant" is included in the list of allowed consequences for the more permissive second hit, but this consequence is not selected in either of these searches. If you select that consequence in annotation secondary only, it is the first variant returned: https://seqr.broadinstitute.org/variant_search/results/86e5e5136ac0226a4c1ab9dc196e448f?page=1&sort=pathogenicity

**Comment by hanars** [comment]
you might want to consider updating the saved permissive search if this is something you  are going to always want to be seeing

**Comment by stephditroia** [comment]
Thanks Hana. I'll bring it to the analysts.

**Comment by stephditroia** [comment]
Hana - do you know how the RNU4ATAC pair is returned in this saved Rec permissive search? Annotations are still missing non coding transcript exon variant. https://seqr.broadinstitute.org/variant_search/results/3952bd665eb4950e9c7fa091921b1b87?page=1&sort=pathogenicity

**Comment by hanars** [comment]
you allow VUS/Conflicting in your pathogenicity filter, so the second hit in that pair is being returned because it matches that criteria. The clinvar override applies to both variants, not just the second hit

**Comment by stephditroia** [comment]
Brilliant. Thank you for investigating. It seems I incorrectly thought our addition of 'non-coding exon variant' fixed this RNU4ATAC problem, but we need to also add 'non coding **transcript** exon variant'. I will bring this up at our next analyst meeting and someone will followup with a new ticket.

**Comment by Caustint** [comment]
Related to this discussion, @hanars do you have a sense of whether the request in  #2804 will be feasible? I think one concern is that adding non coding transcript exon variant returns many additional variant pairs - but I suspect this wouldn't be a problem if we could add just noncoding transcripts that represent the primary transcript for the gene.

**Comment by hanars** [comment]
Its feasible, but it requires changes to the loading pipeline which means it requires Mike to make the change happen and then we would need to reload data for a project before it would be available, so this is just slow and currently its relatively low priority as compared to the other planned pipeline work we have.
